# Value overrides created by the rime_agent terraform module.
%{ if false ~}
# NOTE TO DEVELOPERS: do NOT put default values here! Please put those values in the chart's values.yaml file
%{ endif ~}
rimeAgent:
  image:
    name: "${docker_registry}/${image}:${version}"
%{ if length(image_pull_secret_name) > 0 ~}
  imagePullSecrets:
    - name: ${image_pull_secret_name}
%{ endif ~}

%{ if length(job_manager_server_addr) > 0 ~}
  jobManagerAddr: ${ job_manager_server_addr }
%{ endif ~}
  
%{ if length(agent_manager_server_addr) > 0 ~}
  agentManagerAddr: ${ agent_manager_server_addr }
%{ endif ~}

  modelTestJob:
%{ if length(model_test_job_config_map) > 0 ~}
    configMapName: ${ model_test_job_config_map }
%{ endif ~}
    serviceAccount:
      name: ${ model_test_job_service_account_name }
      annotations: {
        eks.amazonaws.com/role-arn: ${ s3_reader_role_arn }
      }

%{ if length(upload_server_addr) > 0 ~}
    uploadServerAddr: ${ upload_server_addr }
%{ endif ~}
%{ if length(firewall_server_addr) > 0 ~}
    firewallServerAddr: ${ firewall_server_addr }
%{ endif ~}
%{ if length(data_collector_addr) > 0 ~}
    dataCollectorAddr: ${ data_collector_addr }
%{ endif ~}

  launcher:
    requestQueueProxyAddr: ${ request_queue_proxy_addr }
